dart:
	dart day1.dart

go:
	go run day1.go

js:
	node day1.js

python:
	python3 day1.py

rust:
	rustc day1.rs --crate-type bin -o bin/day1_rust.exe && ./bin/day1_rust.exe
	
.PHONY: dart go js python rust