dart:
	dart day4.dart

go:
	go run day4.go

js:
	node day4.js

python:
	python3 day4.py

rust:
	rustc day4.rs --crate-type bin -o bin/day4_rust.exe && ./bin/day4_rust.exe
	
.PHONY: dart go js python rust