dart:
	dart day3.dart

go:
	go run day3.go

js:
	node day3.js

python:
	python3 day3.py

rust:
	rustc day3.rs --crate-type bin -o bin/day3_rust.exe && ./bin/day3_rust.exe
	
.PHONY: dart go js python rust