dart:
	dart day5.dart

go:
	go run day5.go

js:
	node day5.js

python:
	python3 day5.py

rust:
	rustc day5.rs --crate-type bin -o bin/day5_rust.exe && ./bin/day5_rust.exe
	
.PHONY: dart go js python rust