dart:
	dart day2.dart

go:
	go run day2.go

js:
	node day2.js

python:
	python3 day2.py

rust:
	rustc day2.rs --crate-type bin -o bin/day2_rust.exe && ./bin/day2_rust.exe
	
.PHONY: dart go js python rust